package com.cebolao.lotofacil.ui.theme

import androidx.compose.ui.graphics.Color


// Tema Claro (Deep Professional Teal)
val LightPrimary = Color(0xFF006A6A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF6FF5F5)
val LightOnPrimaryContainer = Color(0xFF002020)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E7)
val LightOnSecondaryContainer = Color(0xFF051F1F)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBF9)
val LightOnBackground = Color(0xFF161D1D)
val LightSurface = Color(0xFFF4FBF9)
val LightOnSurface = Color(0xFF161D1D)
val LightSurfaceVariant = Color(0xFFDAE5E3)
val LightOnSurfaceVariant = Color(0xFF3F4948)
val LightOutline = Color(0xFF6F7978)
val LightOutlineVariant = Color(0xFFBECBCA)
val LightSurfaceGlass = Color(0xCCF4FBF9)
val LightPrimaryGlow = Color(0x40006A6A)

// Tema Escuro (Rich Dark Slate)
val DarkPrimary = Color(0xFF4DDADA)
val DarkOnPrimary = Color(0xFF003737)
val DarkPrimaryContainer = Color(0xFF004F4F)
val DarkOnPrimaryContainer = Color(0xFF6FF5F5)
val DarkSecondary = Color(0xFFB0CCCC)
val DarkOnSecondary = Color(0xFF1C3434)
val DarkSecondaryContainer = Color(0xFF324B4B)
val DarkOnSecondaryContainer = Color(0xFFCCE8E7)
val DarkTertiary = Color(0xFFB2C8E8)
val DarkOnTertiary = Color(0xFF1B314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1414)
val DarkOnBackground = Color(0xFFDEE3E2)
val DarkSurface = Color(0xFF0E1414)
val DarkOnSurface = Color(0xFFDEE3E2)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBECBCA)
val DarkOutline = Color(0xFF899392)
val DarkOutlineVariant = Color(0xFF3F4948)
val DarkSurfaceGlass = Color(0xCC0E1414)
val DarkPrimaryGlow = Color(0x604DDADA)